# ──────────────────────────────────────
# Frontend
# ──────────────────────────────────────
frontend:
  replicas: 1
  tag: "v2.1.1"
# ──────────────────────────────────────
# Backend
# ──────────────────────────────────────
backend:
  replicas: 1
  tag: "v2.1.1"
# ──────────────────────────────────────
# MongoDB
# ──────────────────────────────────────
mongo:
  replicas: 2
# ──────────────────────────────────────
# Shared
# ──────────────────────────────────────
ingress_alb:
  host: vanya7.com
# ingress1_nginx:
#  host: myapp.local
