# ──────────────────────────────────────
# Frontend
# ──────────────────────────────────────
frontend:
  replicas: 2
  tag: "v2.1.1"
# ──────────────────────────────────────
# Backend
# ──────────────────────────────────────
backend:
  replicas: 2
  tag: "v2.1.1"
# ──────────────────────────────────────
# MongoDB
# ──────────────────────────────────────
mongo:
  replicas: 2
# ──────────────────────────────────────
# Shared
# ──────────────────────────────────────
ingress_alb:
  host: myapp.local
ingress1_nginx:
  host: myapp.local
